export const CATEGORIES = [
    { id: "all", label: "Explore", icon: "explore" },
    { id: "development", label: "Development", icon: "code" },
    { id: "productivity", label: "Productivity", icon: "check_circle" },
    { id: "gaming", label: "Gaming", icon: "sports_esports" },
    { id: "system", label: "Default Apps", icon: "settings" },
];

export const STORE_dATA = [
    // Development
    {
        id: "ide",
        name: "Nerdy Studio",
        description: "A powerful IDE for web development on NerdyOS. Features syntax highlighting, project management, and git integration.",
        category: "development",
        developer: "NerdyOS Team",
        rating: 4.9,
        size: "120 MB",
        screenshots: ["https://placehold.co/600x400/1e293b/FFF?text=Nerdy+Studio"],
    },
    {
        id: "code_editor",
        name: "Text Editor",
        description: "Lightweight and fast code editor for quick edits. Supports multiple languages.",
        category: "development",
        developer: "Open Source",
        rating: 4.5,
        size: "45 MB",
        screenshots: ["https://placehold.co/600x400/334155/FFF?text=Text+Editor"],
    },
    {
        id: "terminal",
        name: "Terminal",
        description: "Access the powerful underlying command line of NerdyOS.",
        category: "development",
        developer: "NerdyOS Team",
        rating: 4.8,
        size: "5 MB",
    },
    {
        id: "vscode",
        name: "VS Code Web",
        description: "Sleek browser-based editor that displays your codebases using Github1s client integration.",
        category: "development",
        developer: "Microsoft Corp",
        rating: 4.9,
        size: "15 MB",
    },

    // Productivity & Social
    {
        id: "messages",
        name: "WhatsApp Web",
        description: "Chat, send attachments, and view stories online with WhatsApp Web official platform.",
        category: "productivity",
        developer: "Meta Inc",
        rating: 4.7,
        size: "18 MB",
    },
    {
        id: "mail",
        name: "Gmail",
        description: "Send, receive, and browse official mail letters using Gmail cloud inbox.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.6,
        size: "24 MB",
    },
    {
        id: "browser",
        name: "Browser",
        description: "Explore the web with speed and privacy.",
        category: "productivity",
        developer: "Web Co.",
        rating: 4.8,
        size: "150 MB",
    },
    {
        id: "calendar",
        name: "Google Calendar",
        description: "Stay organized and sync schedules online with Google Calendar.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.5,
        size: "8 MB",
    },
    {
        id: "notes",
        name: "Google Keep",
        description: "Keep track of notes, check-lists, and labels using Google Keep online service.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.7,
        size: "6 MB",
    },
    {
        id: "calculator",
        name: "Calculator",
        description: "Simple and scientific calculator for everyday use.",
        category: "productivity",
        developer: "MathTools",
        rating: 4.6,
        size: "8 MB",
    },
    {
        id: "doc",
        name: "Google Docs",
        description: "Create and edit rich documents online using Google Docs official cloud application.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.8,
        size: "12 MB",
    },
    {
        id: "maps",
        name: "Google Maps",
        description: "Search directories, get traffic routes, and explore street maps with Google Maps.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.7,
        size: "35 MB",
    },
    {
        id: "google",
        name: "Google Search",
        description: "Search the web and find information quickly with Google's classic search app integrated inside NerdyOS.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.8,
        size: "1.2 MB",
    },
    {
        id: "gemini",
        name: "Gemini",
        description: "Google's flagship AI chatbot featuring a dark/violet interface and dynamic mock streaming responses.",
        category: "productivity",
        developer: "Google LLC",
        rating: 4.8,
        size: "3.5 MB",
    },
    {
        id: "chatgpt",
        name: "ChatGPT",
        description: "OpenAI's legendary AI chatbot, simulated inside a sleek custom dark client.",
        category: "productivity",
        developer: "OpenAI Inc",
        rating: 4.9,
        size: "3.2 MB",
    },
    {
        id: "office_word",
        name: "Word Web",
        description: "Simulated Microsoft Word editor. Create document layouts, change formatting, and type rich-text articles.",
        category: "productivity",
        developer: "Microsoft Corp",
        rating: 4.6,
        size: "12 MB",
    },
    {
        id: "office_excel",
        name: "Excel Web",
        description: "Interactive spreadsheet mockup. Work with grid cells, write values, and calculate cells dynamically with formula support.",
        category: "productivity",
        developer: "Microsoft Corp",
        rating: 4.7,
        size: "14 MB",
    },
    {
        id: "facebook",
        name: "Facebook",
        description: "Stay connected, join communities, and share content on Facebook Web client.",
        category: "productivity",
        developer: "Meta Inc",
        rating: 4.4,
        size: "22 MB",
    },

    // Gaming & Media
    {
        id: "media",
        name: "Media Player",
        description: "Play music and movies with high fidelity. Supports all modern formats.",
        category: "gaming",
        developer: "Nerdy Media",
        rating: 4.6,
        size: "55 MB",
    },
    {
        id: "photos",
        name: "Google Photos",
        description: "Browse, sort, and save snapshots online with Google Photos.",
        category: "gaming",
        developer: "Google LLC",
        rating: 4.4,
        size: "10 MB",
    },
    {
        id: "pdf_reader",
        name: "PDF Viewer",
        description: "Read, annotate, and sign PDF documents easily.",
        category: "gaming",
        developer: "DocuCorp",
        rating: 4.3,
        size: "30 MB",
    },
    {
        id: "youtube",
        name: "YouTube",
        description: "Watch your favorite videos, channels, and playlists in a beautiful framed client.",
        category: "gaming",
        developer: "Google LLC",
        rating: 4.9,
        size: "4.5 MB",
    },
    {
        id: "pacman",
        name: "Google Pacman",
        description: "Play Google's official interactive 30th anniversary Pacman doodle directly on your desktop.",
        category: "gaming",
        developer: "Google LLC",
        rating: 4.7,
        size: "2.1 MB",
    },
    {
        id: "flappybird",
        name: "Flappy Bird",
        description: "Test your skills in this classic, highly addictive arcade game recreated for web browsers.",
        category: "gaming",
        developer: "Dong Nguyen",
        rating: 4.3,
        size: "0.8 MB",
    },
    {
        id: "instagram",
        name: "Instagram",
        description: "Browse photo streams, search hashtags, and check stories on Instagram Web official client.",
        category: "gaming",
        developer: "Meta Inc",
        rating: 4.5,
        size: "15 MB",
    },

    // Default / System Apps
    {
        id: "monitor",
        name: "System Monitor",
        description: "View system resource usage, processes, and performance metrics.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 4.9,
        size: "10 MB",
    },
    {
        id: "finder",
        name: "Files",
        description: "Manage files and folders on your computer.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 5.0,
        size: "15 MB",
    },
    {
        id: "tasks",
        name: "Tasks",
        description: "Stay organized with to-do lists and project tracking.",
        category: "system",
        developer: "DoIt",
        rating: 4.5,
        size: "20 MB",
    },
    {
        id: "settings",
        name: "Settings",
        description: "Configure your system preferences.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 5.0,
        size: "50 MB",
    }
];
