export const CATEGORIES = [
    { id: "all", label: "All Apps", icon: "apps" },
    { id: "development", label: "Development", icon: "code" },
    { id: "social", label: "Social", icon: "share" },
    { id: "entertainment", label: "Entertainment", icon: "movie" },
    { id: "productivity", label: "Productivity", icon: "check_circle" },
    { id: "system", label: "System", icon: "settings" },
];

export const STORE_dATA = [
    // Development
    {
        id: "ide",
        name: "Nerdy Studio",
        description: "A powerful IDE for web development on NerdyOS. Features syntax highlighting, project management, and git integration.",
        category: "development",
        developer: "NerdyOS Team",
        rating: 4.9,
        size: "120 MB",
        screenshots: ["https://placehold.co/600x400/1e293b/FFF?text=Nerdy+Studio"],
    },
    {
        id: "code_editor",
        name: "Text Editor",
        description: "Lightweight and fast code editor for quick edits. Supports multiple languages.",
        category: "development",
        developer: "Open Source",
        rating: 4.5,
        size: "45 MB",
        screenshots: ["https://placehold.co/600x400/334155/FFF?text=Text+Editor"],
    },
    {
        id: "terminal",
        name: "Terminal",
        description: "Access the powerful underlying command line of NerdyOS.",
        category: "development",
        developer: "NerdyOS Team",
        rating: 4.8,
        size: "5 MB",
    },

    // Social
    {
        id: "messages",
        name: "Messages",
        description: "Stay connected with friends and colleagues. Send text, images, and files securely.",
        category: "social",
        developer: "Nerdy Comm",
        rating: 4.7,
        size: "60 MB",
    },
    {
        id: "mail",
        name: "Mail",
        description: "Manage all your email accounts in one place. Fast, searching, and secure.",
        category: "social",
        developer: "PostMaster",
        rating: 4.2,
        size: "80 MB",
    },

    // Entertainment / Media
    {
        id: "media",
        name: "Media Player",
        description: "Play music and movies with high fidelity. Supports all modern formats.",
        category: "entertainment",
        developer: "Nerdy Media",
        rating: 4.6,
        size: "55 MB",
    },
    {
        id: "photos",
        name: "Photos",
        description: "Organize, edit, and share your photo collection.",
        category: "entertainment",
        developer: "PixelSoft",
        rating: 4.4,
        size: "90 MB",
    },
    {
        id: "pdf_reader",
        name: "PDF Viewer",
        description: "Read, annotate, and sign PDF documents easily.",
        category: "productivity",
        developer: "DocuCorp",
        rating: 4.3,
        size: "30 MB",
    },

    // Productivity / Tools
    {
        id: "monitor",
        name: "System Monitor",
        description: "View system resource usage, processes, and performance metrics.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 4.9,
        size: "10 MB",
    },
    {
        id: "finder",
        name: "Files",
        description: "Manage files and folders on your computer.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 5.0,
        size: "15 MB",
    },
    {
        id: "browser",
        name: "Browser",
        description: "Explore the web with speed and privacy.",
        category: "productivity",
        developer: "Web Co.",
        rating: 4.8,
        size: "150 MB",
    },
    {
        id: "calendar",
        name: "Calendar",
        description: "Schedule meetings, events, and reminders.",
        category: "productivity",
        developer: "TimeKeeper",
        rating: 4.5,
        size: "40 MB",
    },
    {
        id: "notes",
        name: "Notes",
        description: "Capture your ideas quickly and sync them across devices.",
        category: "productivity",
        developer: "InkWell",
        rating: 4.7,
        size: "25 MB",
    },
    {
        id: "calculator",
        name: "Calculator",
        description: "Simple and scientific calculator for everyday use.",
        category: "productivity",
        developer: "MathTools",
        rating: 4.6,
        size: "8 MB",
    },
    {
        id: "doc",
        name: "Nerdy Doc",
        description: "Create and edit rich text documents compatible with standard formats.",
        category: "productivity",
        developer: "NerdyOffice",
        rating: 4.4,
        size: "110 MB",
    },
    {
        id: "maps",
        name: "Maps",
        description: "Explore the world, get directions, and find local businesses.",
        category: "productivity",
        developer: "GeoSoft",
        rating: 4.3,
        size: "95 MB",
    },
    {
        id: "tasks",
        name: "Tasks",
        description: "Stay organized with to-do lists and project tracking.",
        category: "productivity",
        developer: "DoIt",
        rating: 4.5,
        size: "20 MB",
    },
    {
        id: "settings",
        name: "Settings",
        description: "Configure your system preferences.",
        category: "system",
        developer: "NerdyOS Team",
        rating: 5.0,
        size: "50 MB",
    }
];
