import NerdyFiles from "../apps/NerdyFiles/NerdyFiles";
import NerdySettings from "../apps/NerdySettings/NerdySettings";
import NerdyBrowser from "../apps/NerdyBrowser/NerdyBrowser";
import NerdyShell from "../apps/NerdyShell/NerdyShell";
import NerdyCalc from "../apps/NerdyCalc/NerdyCalc";
import NerdyMedia from "../apps/NerdyMedia/NerdyMedia";
import NerdyStore from "../apps/NerdyStore/NerdyStore";
import SystemMonitor from "../apps/SystemMonitor/SystemMonitor";
import NerdyStudio from "../apps/NerdyStudio/NerdyStudio";
import NerdyTextEditor from "../apps/NerdyTextEditor/NerdyTextEditor";
import NerdyTasks from "../apps/NerdyTasks/NerdyTasks";
import NerdyPDF from "../apps/NerdyPDF/NerdyPDF";
import NerdyAI from "../apps/NerdyAI/NerdyAI";
import { WebWrapperApp } from "../apps/WebApps/WebApps";

export const APP_REGISTRY = {
  finder: {
    id: "finder",
    name: "Files",
    icon: "folder",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/finder.png",
    component: NerdyFiles,
    defaultSize: { width: 900, height: 600 },
    color: "bg-[#1C8DFF]",
  },
  settings: {
    id: "settings",
    name: "Settings",
    icon: "settings",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/settings.png",
    component: NerdySettings,
    defaultSize: { width: 900, height: 650 },
    color: "bg-[#5D6672]",
  },
  browser: {
    id: "browser",
    name: "Browser",
    icon: "globe",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/safari.png",
    component: NerdyBrowser,
    defaultSize: { width: 1000, height: 700 },
    color: "bg-[#0A84FF]",
  },
  terminal: {
    id: "terminal",
    name: "Terminal",
    icon: "computer",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/terminal.png",
    component: NerdyShell,
    defaultSize: { width: 700, height: 500 },
    color: "bg-black border border-white/10",
  },
  calculator: {
    id: "calculator",
    name: "Calculator",
    icon: "calculate",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/calculator.png",
    component: NerdyCalc,
    defaultSize: { width: 300, height: 450 },
    color: "bg-[#F39C12]",
  },
  media: {
    id: "media",
    name: "Media Player",
    icon: "play_circle",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/quicktime-player.png",
    component: NerdyMedia,
    defaultSize: { width: 800, height: 500 },
    color: "bg-[#2C3E50]",
  },
  doc: {
    id: "doc",
    name: "Google Docs",
    icon: "article",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/pages.png",
    component: WebWrapperApp,
    defaultSize: { width: 900, height: 600 },
    color: "bg-[#2ECC71]",
  },
  store: {
    id: "store",
    name: "App Store",
    icon: "bag",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/app-store.png",
    component: NerdyStore,
    defaultSize: { width: 950, height: 600 },
    color: "bg-gradient-to-br from-blue-500 to-indigo-600",
  },
  notes: {
    id: "notes",
    name: "Google Keep",
    icon: "note",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/notes.png",
    component: WebWrapperApp,
    defaultSize: { width: 600, height: 400 },
    color: "bg-[#F1C40F]",
  },
  calendar: {
    id: "calendar",
    name: "Google Calendar",
    icon: "calendar_month",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/calendar.png",
    component: WebWrapperApp,
    defaultSize: { width: 900, height: 600 },
    color: "bg-[#E74C3C]",
  },
  monitor: {
    id: "monitor",
    name: "System Monitor",
    icon: "monitoring",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/activity-monitor.png",
    component: SystemMonitor,
    defaultSize: { width: 500, height: 400 },
    color: "bg-[#27AE60]",
  },
  messages: {
    id: "messages",
    name: "WhatsApp Web",
    icon: "forum",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/733/733585.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 650 },
    color: "bg-[#25D366]",
  },
  mail: {
    id: "mail",
    name: "Gmail",
    icon: "mail",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/mail.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#3498DB]",
  },
  maps: {
    id: "maps",
    name: "Google Maps",
    icon: "map",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/maps.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#1ABC9C]",
  },
  photos: {
    id: "photos",
    name: "Google Photos",
    icon: "photo",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/photos.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#9B59B6]",
  },
  ide: {
    id: "ide",
    name: "Nerdy Studio",
    icon: "code",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/xcode.png",
    component: NerdyStudio,
    defaultSize: { width: 1100, height: 700 },
    color: "bg-[#2980B9]",
  },
  code_editor: {
    id: "code_editor",
    name: "Text Editor",
    icon: "edit_note",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/textedit.png",
    component: NerdyTextEditor,
    defaultSize: { width: 800, height: 600 },
    color: "bg-[#7F8C8D]",
  },
  tasks: {
    id: "tasks",
    name: "Tasks",
    icon: "check_circle",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/reminders.png",
    component: NerdyTasks,
    defaultSize: { width: 400, height: 500 },
    color: "bg-[#8E44AD]",
  },
  pdf_reader: {
    id: "pdf_reader",
    name: "PDF Viewer",
    icon: "picture_as_pdf",
    iconUrl: "https://raw.githubusercontent.com/Keycap/macOS-Simple-Icons/main/icons/preview.png",
    component: NerdyPDF,
    defaultSize: { width: 800, height: 900 },
    color: "bg-[#C0392B]",
  },
  ai: {
    id: "ai",
    name: "Nerdy AI",
    icon: "sparkles",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Google_Gemini_logo.svg",
    component: NerdyAI,
    defaultSize: { width: 700, height: 550 },
    color: "bg-[#6C5CE7]",
  },
  youtube: {
    id: "youtube",
    name: "YouTube",
    icon: "play_circle",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/1384/1384060.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#FF0000]",
  },
  google: {
    id: "google",
    name: "Google Search",
    icon: "globe",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/300/300221.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#4285F4]",
  },
  pacman: {
    id: "pacman",
    name: "Google Pacman",
    icon: "play_circle",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/5690/5690520.png",
    component: WebWrapperApp,
    defaultSize: { width: 640, height: 480 },
    color: "bg-[#F1C40F]",
  },
  flappybird: {
    id: "flappybird",
    name: "Flappy Bird",
    icon: "check_circle",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/5261/5261929.png",
    component: WebWrapperApp,
    defaultSize: { width: 480, height: 640 },
    color: "bg-[#E67E22]",
  },
  vscode: {
    id: "vscode",
    name: "VS Code Web",
    icon: "code",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/906/906324.png",
    component: WebWrapperApp,
    defaultSize: { width: 1100, height: 700 },
    color: "bg-[#007ACC]",
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    icon: "sparkles",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/12222/12222353.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#1A73E8]",
  },
  chatgpt: {
    id: "chatgpt",
    name: "ChatGPT",
    icon: "forum",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/12222/12222588.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#10A37F]",
  },
  office_word: {
    id: "office_word",
    name: "Word Web",
    icon: "article",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/732/732220.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 650 },
    color: "bg-[#2B579A]",
  },
  office_excel: {
    id: "office_excel",
    name: "Excel Web",
    icon: "monitoring",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/732/732200.png",
    component: WebWrapperApp,
    defaultSize: { width: 1000, height: 650 },
    color: "bg-[#217346]",
  },
  instagram: {
    id: "instagram",
    name: "Instagram",
    icon: "photo",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/174/174855.png",
    component: WebWrapperApp,
    defaultSize: { width: 450, height: 750 },
    color: "bg-[#E1306C]",
  },
  facebook: {
    id: "facebook",
    name: "Facebook",
    icon: "globe",
    iconUrl: "https://cdn-icons-png.flaticon.com/512/124/124010.png",
    component: WebWrapperApp,
    defaultSize: { width: 950, height: 600 },
    color: "bg-[#1877F2]",
  },
};

export const getAppById = (id) => APP_REGISTRY[id];

export default APP_REGISTRY;
